/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsiteAnalyzerRouteImport } from './routes/website-analyzer'
import { Route as TrafficCheckerRouteImport } from './routes/traffic-checker'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SeoAnalyzerRouteImport } from './routes/seo-analyzer'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as FreeAuditRouteImport } from './routes/free-audit'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as BookCallRouteImport } from './routes/book-call'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WebsiteAnalyzerRoute = WebsiteAnalyzerRouteImport.update({
  id: '/website-analyzer',
  path: '/website-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const TrafficCheckerRoute = TrafficCheckerRouteImport.update({
  id: '/traffic-checker',
  path: '/traffic-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoAnalyzerRoute = SeoAnalyzerRouteImport.update({
  id: '/seo-analyzer',
  path: '/seo-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeAuditRoute = FreeAuditRouteImport.update({
  id: '/free-audit',
  path: '/free-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const BookCallRoute = BookCallRouteImport.update({
  id: '/book-call',
  path: '/book-call',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/book-call': typeof BookCallRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/free-audit': typeof FreeAuditRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/seo-analyzer': typeof SeoAnalyzerRoute
  '/services': typeof ServicesRoute
  '/testimonials': typeof TestimonialsRoute
  '/traffic-checker': typeof TrafficCheckerRoute
  '/website-analyzer': typeof WebsiteAnalyzerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/book-call': typeof BookCallRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/free-audit': typeof FreeAuditRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/seo-analyzer': typeof SeoAnalyzerRoute
  '/services': typeof ServicesRoute
  '/testimonials': typeof TestimonialsRoute
  '/traffic-checker': typeof TrafficCheckerRoute
  '/website-analyzer': typeof WebsiteAnalyzerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/book-call': typeof BookCallRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/free-audit': typeof FreeAuditRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/seo-analyzer': typeof SeoAnalyzerRoute
  '/services': typeof ServicesRoute
  '/testimonials': typeof TestimonialsRoute
  '/traffic-checker': typeof TrafficCheckerRoute
  '/website-analyzer': typeof WebsiteAnalyzerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/book-call'
    | '/case-studies'
    | '/contact'
    | '/free-audit'
    | '/portfolio'
    | '/pricing'
    | '/seo-analyzer'
    | '/services'
    | '/testimonials'
    | '/traffic-checker'
    | '/website-analyzer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/book-call'
    | '/case-studies'
    | '/contact'
    | '/free-audit'
    | '/portfolio'
    | '/pricing'
    | '/seo-analyzer'
    | '/services'
    | '/testimonials'
    | '/traffic-checker'
    | '/website-analyzer'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/book-call'
    | '/case-studies'
    | '/contact'
    | '/free-audit'
    | '/portfolio'
    | '/pricing'
    | '/seo-analyzer'
    | '/services'
    | '/testimonials'
    | '/traffic-checker'
    | '/website-analyzer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  BookCallRoute: typeof BookCallRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  FreeAuditRoute: typeof FreeAuditRoute
  PortfolioRoute: typeof PortfolioRoute
  PricingRoute: typeof PricingRoute
  SeoAnalyzerRoute: typeof SeoAnalyzerRoute
  ServicesRoute: typeof ServicesRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TrafficCheckerRoute: typeof TrafficCheckerRoute
  WebsiteAnalyzerRoute: typeof WebsiteAnalyzerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/website-analyzer': {
      id: '/website-analyzer'
      path: '/website-analyzer'
      fullPath: '/website-analyzer'
      preLoaderRoute: typeof WebsiteAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traffic-checker': {
      id: '/traffic-checker'
      path: '/traffic-checker'
      fullPath: '/traffic-checker'
      preLoaderRoute: typeof TrafficCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-analyzer': {
      id: '/seo-analyzer'
      path: '/seo-analyzer'
      fullPath: '/seo-analyzer'
      preLoaderRoute: typeof SeoAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-audit': {
      id: '/free-audit'
      path: '/free-audit'
      fullPath: '/free-audit'
      preLoaderRoute: typeof FreeAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-call': {
      id: '/book-call'
      path: '/book-call'
      fullPath: '/book-call'
      preLoaderRoute: typeof BookCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  BookCallRoute: BookCallRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  FreeAuditRoute: FreeAuditRoute,
  PortfolioRoute: PortfolioRoute,
  PricingRoute: PricingRoute,
  SeoAnalyzerRoute: SeoAnalyzerRoute,
  ServicesRoute: ServicesRoute,
  TestimonialsRoute: TestimonialsRoute,
  TrafficCheckerRoute: TrafficCheckerRoute,
  WebsiteAnalyzerRoute: WebsiteAnalyzerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
